export const Countries = [
    {'AFG': 'Afghanistan'},
    {'ALB': 'Albania'},
    {'DZA': 'Algeria'},
    {'AND': 'Andorra'},
    {'AGO': 'Angola'},
    {'ACA': 'Antigua and Barbuda'},
    {'ARG': 'Argentina'},
    {'ARM': 'Armenia'},
    {'AUZ': 'Australia'},
    {'AUT': 'Austria'},
    {'AZE': 'Azerbaijan'},
    {'BHS': 'Bahamas'},
    {'BHR': 'Bahrain'},
    {'BGD': 'Bangladesh'},
    {'BRB': 'Barbados'},
    {'BLR': 'Belarus'},
    {'BCR': 'Belgium'},
    {'BLZ': 'Belize'},
    {'BEN': 'Benin'},
    {'BTN': 'Bhutan'},
    {'BOL': 'Bolivia'},
    {'BHF': 'Bosnia Herzegovina'},
    {'BWA': 'Botswana'},
    {'BRA': 'Brazil'},
    {'BRN': 'Brunei'},
    {'BGR': 'Bulgaria'},
    {'BFA': 'Burkina Faso'},
    {'BDI': 'Burundi'},
    {'KHM': 'Cambodia'},
    {'CMR': 'Cameroon'},
    {'CAN': 'Canada'},
    {'CPV': 'Cape Verde'},
    {'CAF': 'Central African Republic'},
    {'TCD': 'Chad'},
    {'CHX': 'Chile'},
    {'CHI': 'China'},
    {'COL': 'Colombia'},
    {'COM': 'Comoros'},
    {'CRI': 'Costa Rica'},
    {'CIV': "Cote d'Ivoire"},
    {'HRV': 'Croatia'},
    {'CUB': 'Cuba'},
    {'CYP': 'Cyprus'},
    {'CZE': 'Czech Republic'},
    {'COD': 'Democratic Republic of Congo'},
    {'DNK': 'Denmark'},
    {'DJI': 'Djibouti'},
    {'DMA': 'Dominica'},
    {'DOM': 'Dominican Republic'},
    {'ECD': 'Ecuador'},
    {'EGY': 'Egypt'},
    {'SLV': 'El Salvador'},
    {'GNA': 'Equatorial Guinea'},
    {'ERI': 'Eritrea'},
    {'EST': 'Estonia'},
    {'ETH': 'Ethiopia'},
    {'FJI': 'Fiji'},
    {'FIN': 'Finland'},
    {'FXX': 'France'},
    {'GAB': 'Gabon'},
    {'GMB': 'Gambia'},
    {'GEG': 'Georgia'},
    {'DEU': 'Germany'},
    {'GHA': 'Ghana'},
    {'GRC': 'Greece'},
    {'GRD': 'Grenada'},
    {'GTM': 'Guatemala'},
    {'GIN': 'Guinea'},
    {'GNB': 'Guinea Bissau'},
    {'GUY': 'Guyana'},
    {'HTI': 'Haiti'},
    {'HND': 'Honduras'},
    {'HUN': 'Hungary'},
    {'ISL': 'Iceland'},
    {'INX': 'India'},
    {'IDN': 'Indonesia'},
    {'IRN': 'Iran'},
    {'IRR': 'Iraq'},
    {'IRL': 'Ireland'},
    {'ISR': 'Israel'},
    {'ITA': 'Italy'},
    {'JAM': 'Jamaica'},
    {'JPX': 'Japan'},
    {'JOR': 'Jordan'},
    {'KAZ': 'Kazakhstan'},
    {'KEN': 'Kenya'},
    {'KIR': 'Kiribati'},
    {'KOS': 'Kosovo'},
    {'KWT': 'Kuwait'},
    {'KGZ': 'Kyrgyzstan'},
    {'LAO': 'Laos'},
    {'LVA': 'Latvia'},
    {'LBN': 'Lebanon'},
    {'LSO': 'Lesotho'},
    {'LBR': 'Liberia'},
    {'LBY': 'Libya'},
    {'LIE': 'Liechtenstein'},
    {'LTU': 'Lithuania'},
    {'LUX': 'Luxembourg'},
    {'MKD': 'Macedonia'},
    {'MDG': 'Madagascar'},
    {'MWI': 'Malawi'},
    {'MYS': 'Malaysia'},
    // {'MDV': 'Maldives'},
    {'MLI': 'Mali'},
    {'MLT': 'Malta'},
    {'MHL': 'Marshall Islands'},
    {'MRT': 'Mauritania'},
    // {'MUS': 'Mauritius'},
    {'MEX': 'Mexico'},
    {'FSM': 'Micronesia'},
    {'MDA': 'Moldova'},
    {'MCO': 'Monaco'},
    {'MNG': 'Mongolia'},
    {'MNE': 'Montenegro'},
    {'MAR': 'Morocco'},
    {'MOZ': 'Mozambique'},
    {'MMR': 'Myanmar'},
    {'NAM': 'Namibia'},
    {'NRU': 'Nauru'},
    {'NPL': 'Nepal'},
    {'NLX': 'Netherlands'},
    {'NZN': 'New Zealand'},
    {'NIC': 'Nicaragua'},
    {'NER': 'Niger'},
    {'NGA': 'Nigeria'},
    {'KNZ': 'North Korea'},
    {'NOW': 'Norway'},
    {'OMN': 'Oman'},
    {'PAK': 'Pakistan'},
    {'PLW': 'Palau'},
    {'WEB': 'Palestine'},
    {'PAN': 'Panama'},
    {'PNX': 'Papua New Guinea'},
    {'PRY': 'Paraguay'},
    {'PER': 'Peru'},
    {'PHI': 'Philippines'},
    {'POL': 'Poland'},
    {'PRX': 'Portugal'},
    {'QAT': 'Qatar'},
    {'COG': 'Republic of Congo'},
    {'ROU': 'Romania'},
    {'RUS': 'Russia'},
    {'RWA': 'Rwanda'},
    {'KNA': 'Saint Kitts and Nevis'},
    {'LCA': 'Saint Lucia'},
    {'VCT': 'Saint Vincent'},
    {'WSM': 'Samoa'},
    {'SMR': 'San Marino'},
    {'STS': 'Sao Tome and Principe'},
    {'SAU': 'Saudi Arabia'},
    {'SEN': 'Senegal'},
    {'SER': 'Serbia'},
    // {'SYC': 'Seychelles'},
    {'SLE': 'Sierra Leone'},
    {'SGP': 'Singapore'},
    {'SVK': 'Slovakia'},
    {'SVN': 'Slovenia'},
    {'SLB': 'Solomon Islands'},
    {'SOX': 'Somalia'},
    {'ZAX': 'South Africa'},
    {'KNX': 'South Korea'},
    {'SDS': 'South Sudan'},
    {'ESX': 'Spain'},
    {'LKA': 'Sri Lanka'},
    {'SDN': 'Sudan'},
    {'SUR': 'Suriname'},
    {'SWZ': 'Swaziland'},
    {'SWE': 'Sweden'},
    {'CHE': 'Switzerland'},
    {'SYX': 'Syria'},
    {'TWN': 'Taiwan'},
    {'TJK': 'Tajikistan'},
    {'TZA': 'Tanzania'},
    {'THA': 'Thailand'},
    {'TLX': 'Timor Leste'},
    {'TGO': 'Togo'},
    {'TON': 'Tonga'},
    {'TTD': 'Trinidad and Tobago'},
    {'TUN': 'Tunisia'},
    {'TUR': 'Turkey'},
    {'TKM': 'Turkmenistan'},
    {'TUV': 'Tuvalu'},
    {'UGA': 'Uganda'},
    {'ENG': 'UK'},
    {'UKR': 'Ukraine'},
    {'ARE': 'UAE'},
    {'URY': 'Uruguay'},
    {'USB': 'Usa'},
    {'UZB': 'Uzbekistan'},
    {'VUT': 'Vanuatu'},
    {'VAT': 'Vatican'},
    {'VEN': 'Venezuela'},
    {'VNM': 'Vietnam'},
    {'YEM': 'Yemen'},
    {'ZMB': 'Zambia'},
    {'ZWE': 'Zimbabwe'}
];
